# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ directplay ]
  pull_request:
    branches: [ directplay ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.19.3]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.5.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm install
    
    - run: npm run build:production
    
    - name: Zip artifact for deployment
      run: 7z a Jellyfin-web.7z ./dist/* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: Jellyfin-web
        path: Jellyfin-web.7z
